## Analysis of the problem statement

### Problem statement

I have a python dataframe with a string column and my purposes is to separate into several more columns. Plus to extract numerical values in sn_remarks columns.

Lets first understand the data set provided and using that dataset we will try to understand the above problem in Machine Learning world. Since, the dataset is huge lets load it using python itself

In [2]:
# load the first file for july dataset.
import pandas as pd
import numpy as np
import sys
sn_remarks = pd.read_excel(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\20190725_July_SRC_Main_List.xlsx")

keep doing more analysis on above data

In [4]:
## Clecking column in above data set
sn_remarks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17918 entries, 0 to 17917
Data columns (total 88 columns):
State                                 17918 non-null object
State Description                     17918 non-null object
Business Area - Key                   17918 non-null int64
Channel                               17918 non-null object
Complaint ID                          17918 non-null int64
CA Number                             17918 non-null int64
Unit                                  17918 non-null object
Category                              17918 non-null object
Sub-Category                          17918 non-null object
Creation Date                         17918 non-null datetime64[ns]
SN Number                             17918 non-null object
SO Number                             17918 non-null object
BPEM Case                             17918 non-null object
Notes                                 17918 non-null object
SN Remarks 25July                     15796 non-null object
BPEM Notes 24July                     1308 non-null object
Feedback Status                       15853 non-null object
Status 25July                         17918 non-null object
Verified Root Cause Type              15659 non-null object
Verified Root Cause                   15659 non-null object
Root Cause Measure                    15659 non-null object
Refund/Arrears                        2699 non-null object
Dt/Cr Amount                          2699 non-null float64
MB Reason                             807 non-null object
SO transfer to SN                     1732 non-null object
JAN_TOTAL_KWH_2019                    12211 non-null float64
FEB_TOTAL_KWH_2019                    15305 non-null float64
MAR_TOTAL_KWH_2019                    15405 non-null float64
APR_TOTAL_KWH_2019                    15520 non-null float64
MAY_TOTAL_KWH_2019                    15647 non-null float64
JUN_TOTAL_KWH_2019                    15707 non-null float64
JUL_BILL_DATE_2019                    11986 non-null float64
JUL_BILL_DURATION_2019                11986 non-null float64
JUL_BILL_TYPE_2019                    11986 non-null object
JUL_TARIF_TYPE                        11986 non-null object
JUL_READING_TYPE_2019                 11986 non-null object
JUL_OUTSTANDING_AMOUNT_2019           11986 non-null float64
JUL_CURRENT_CHARGES_2019              11986 non-null float64
JUL_TOTAL_BILL_2019                   11986 non-null float64
JUL_TOTAL_KWH_2019                    11986 non-null float64
JUL_BILLING_PERIOD_START_DATE_2019    11986 non-null float64
JUL_BILLING_PERIOD_END_DATE_2019      11986 non-null float64
JUL_PORTION_2019                      11986 non-null object
READING_TYPE_ENRICHMENT               15853 non-null object
Contains..FIN.                        15853 non-null float64
no.of.NA.s                            17918 non-null object
JAN2019_BAND                          12211 non-null float64
FEB2019_BAND                          15305 non-null float64
MAR2019_BAND                          15405 non-null float64
APR2019_BAND                          15520 non-null float64
MAY2019_BAND                          15647 non-null float64
JUN2019_BAND                          15707 non-null float64
JUL2019_BAND                          11986 non-null float64
JAN2019_BANDRANGE                     12211 non-null object
FEB2019_BANDRANGE                     15305 non-null object
MAR2019_BANDRANGE                     15405 non-null object
APR2019_BANDRANGE                     15520 non-null object
MAY2019_BANDRANGE                     15647 non-null object
JUN2019_BANDRANGE                     15707 non-null object
JUL2019_BANDRANGE                     11986 non-null object
FEB_KWH.Increase                      12206 non-null object
MAR_KWH.Increase                      15293 non-null object
APR_KWH.Increase                      15392 non-null object
MAY_KWH.Increase                      15516 non-null object
JUN_KWH.Increase                      15637 non-null object
JUL_KWH.Increase                      12056 non-null object
FEB2019_BANDCHANGE                    12205 non-null float64
MAR2019_BANDCHANGE                    15293 non-null float64
APR2019_BANDCHANGE                    15390 non-null float64
MAY2019_BANDCHANGE                    15515 non-null float64
JUN2019_BANDCHANGE                    15635 non-null float64
JUL2019_BANDCHANGE                    11925 non-null float64
FEB2019_CC.INCREASE                   12205 non-null object
MAR2019_CC.INCREASE                   15293 non-null object
APR2019_CC.INCREASE                   14972 non-null object
MAY2019_CC.INCREASE                   15517 non-null object
JUN2019_CC.INCREASE                   15637 non-null object
JUL2019_CC.INCREASE                   11958 non-null object
BILL_TYPE                             15853 non-null object
TARRIFTYPE                            15853 non-null object
READING_TYPE                          15853 non-null object
PORTION                               15853 non-null object
1                                     3400 non-null object
2                                     3400 non-null object
3                                     3400 non-null object
4                                     3400 non-null object
5                                     3400 non-null float64
6                                     3400 non-null object
dtypes: datetime64[ns](1), float64(30), int64(3), object(54)
memory usage: 12.0+ MB

In [8]:
# Checking dimention of data
sn_remarks.shape

(17918, 88)

In [10]:
# missing values in companies df
sn_remarks.isnull().sum()

State                           0
State_Description               0
Business_Area___Key             0
Channel                         0
Complaint_ID                    0
CA_Number                       0
Unit                            0
Category                        0
Sub_Category                    0
Creation_Date                   0
SN_Number                       0
SO_Number                       0
BPEM_Case                       0
Notes                           0
SN_Remarks_25July            2122
BPEM_Notes_24July           16610
Feedback_Status              2065
Status_25July                   0
Verified_Root_Cause_Type     2259
Verified_Root_Cause          2259
Root_Cause_Measure           2259
Refund/Arrears              15219
Dt/Cr_Amount                15219
MB_Reason                   17111
SO_transfer_to_SN           16186
JAN_TOTAL_KWH_2019           5707
FEB_TOTAL_KWH_2019           2613
MAR_TOTAL_KWH_2019           2513
APR_TOTAL_KWH_2019           2398
MAY_TOTAL_KWH_2019           2271
                            ...
JUN2019_BANDRANGE            2211
JUL2019_BANDRANGE            5932
FEB_KWH.Increase             5712
MAR_KWH.Increase             2625
APR_KWH.Increase             2526
MAY_KWH.Increase             2402
JUN_KWH.Increase             2281
JUL_KWH.Increase             5862
FEB2019_BANDCHANGE           5713
MAR2019_BANDCHANGE           2625
APR2019_BANDCHANGE           2528
MAY2019_BANDCHANGE           2403
JUN2019_BANDCHANGE           2283
JUL2019_BANDCHANGE           5993
FEB2019_CC.INCREASE          5713
MAR2019_CC.INCREASE          2625
APR2019_CC.INCREASE          2946
MAY2019_CC.INCREASE          2401
JUN2019_CC.INCREASE          2281
JUL2019_CC.INCREASE          5960
BILL_TYPE                    2065
TARRIFTYPE                   2065
READING_TYPE                 2065
PORTION                      2065
NaN                         14518
NaN                         14518
NaN                         14518
NaN                         14518
NaN                         14518
NaN                         14518
Length: 88, dtype: int64

In [9]:
sn_remarks.head()
sn_remarks.tail()

,State,State_Description,Business_Area___Key,Channel,Complaint_ID,CA_Number,Unit,Category,Sub_Category,Creation_Date,...,BILL_TYPE,TARRIFTYPE,READING_TYPE,PORTION,nan,nan,nan,nan,nan,nan
17913,PIN,PULAU PINANG,6260,Self Service Portal,1000758762,220583476302,MRU - OPC,Check Meter Reading,Bill Too High,2019-07-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17914,PIN,PULAU PINANG,6260,Self Service Portal,1000758768,220573233202,MRU - OPC,Check Meter Reading,Bill Too High,2019-07-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17915,PIN,PULAU PINANG,6260,TNB Website,1000758781,220592165900,MRU - OPC,Check Meter Reading,Bill Too High,2019-07-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17916,PIN,PULAU PINANG,6261,Careline,1000758792,220468480705,MRU - OPC,Check Meter Reading,Bill Too High,2019-07-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17917,PIN,PULAU PINANG,6261,Kedai Tenaga,1000756061,220418251105,Device Operation (OPC),OPC Meter Accuracy Test,High Bill Normal,2019-07-19,...,NaN,NaN,NaN,NaN,H - Further Investigation,MIT,NO ACTION,0,0.0,0

give the proper table structure columns name

In [6]:
sn_remarks.columns = sn_remarks.columns.str.replace(' ','_')

In [7]:
sn_remarks.columns = sn_remarks.columns.str.replace('-','_')

Ok, now we understood the dataset. Lets try to understand how to meet the objective to capture the SO/SN number in sn_remarks column.

In [11]:
# https://stackoverflow.com/questions/51833930/how-should-i-remove-special-characters-from-data-frame-except-space
sn_remarks['SN_Remarks_25July'] = sn_remarks['SN_Remarks_25July'].str.replace(r"[^a-zA-Z0-9 ]+", " ").str.strip()

In [12]:
sn_remarks['clean_sn_remark'] = sn_remarks['SN_Remarks_25July'].str.upper()

In [13]:
sn_remarks.head()

,State,State_Description,Business_Area___Key,Channel,Complaint_ID,CA_Number,Unit,Category,Sub_Category,Creation_Date,...,TARRIFTYPE,READING_TYPE,PORTION,nan,nan,nan,nan,nan,nan,clean_sn_remark
0,KUL,WP KUALA LUMPUR,6123,Careline,2000126819,220034296310,MRU - OPC,Estimated Bill,Premise / Gate Not Locked,2019-07-11,...,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,SPOT12-SPOT12-SPOT12-SPOT12-SPOT12-SPOT12-SPOT12,NaN,NaN,NaN,NaN,NaN,NaN,INTERNAL NOTE 11 07 2019 16 46 37 ...
1,KUL,WP KUALA LUMPUR,6123,Careline,2000127122,220187543106,Billing - LPC,Bill Received,Bill Not Received,2019-07-14,...,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KUL,WP KUALA LUMPUR,6123,Careline,2000127225,220188432308,Billing - LPC,Bill Received,Bill Not Received,2019-07-15,...,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JOH,JOHOR,6340,Careline,2000125572,220728929002,Billing - LPC,Bill Received,Bill Not Received,2019-07-03,...,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NSE,NEGERI SEMBILAN,6320,Careline,2000127271,210108059707,MRU - OPC,Estimated Bill,Premise / Gate Not Locked,2019-07-15,...,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-ACT-ACT-EST-ACT-EST,SPOT11-SPOT11-SPOT11-SPOT11-SPOT11-SPOT11-SPOT11,NaN,NaN,NaN,NaN,NaN,NaN,INTERNAL NOTE15 07 2019 14 22 53 60068166PENGG...

In [14]:
from nltk.tokenize import word_tokenize
from nltk.util import ngrams
def get_ngrams(text, n):
    #n = 3
    n_grams = ngrams(word_tokenize(text), n)
    return [ ' '.join(grams) for grams in n_grams]

sn_remarks['clean_sn_remark_grams1']  = sn_remarks['clean_sn_remark'].astype(str).apply(get_ngrams, n=1)
sn_remarks['clean_sn_remark_grams2']  = sn_remarks['clean_sn_remark'].astype(str).apply(get_ngrams, n=2)
sn_remarks['clean_sn_remark_grams3']  = sn_remarks['clean_sn_remark'].astype(str).apply(get_ngrams, n=3)
#sn_remarks['clean_sn_remark_grams4']  = sn_remarks['clean_sn_remark'].astype(str).apply(get_ngrams, n=4)

In [15]:
sn_remarks['clean_sn_remark_grams'] = sn_remarks['clean_sn_remark_grams1'] + sn_remarks['clean_sn_remark_grams2'] +sn_remarks['clean_sn_remark_grams3']# + sn_remarks['clean_sn_remark_grams4']

In [16]:
del sn_remarks['clean_sn_remark_grams1']
del sn_remarks['clean_sn_remark_grams2']
del sn_remarks['clean_sn_remark_grams3']
#del sn_remarks['clean_sn_remark_grams4']

In [17]:
sn_remarks.head()

,State,State_Description,Business_Area___Key,Channel,Complaint_ID,CA_Number,Unit,Category,Sub_Category,Creation_Date,...,READING_TYPE,PORTION,nan,nan,nan,nan,nan,nan,clean_sn_remark,clean_sn_remark_grams
0,KUL,WP KUALA LUMPUR,6123,Careline,2000126819,220034296310,MRU - OPC,Estimated Bill,Premise / Gate Not Locked,2019-07-11,...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,SPOT12-SPOT12-SPOT12-SPOT12-SPOT12-SPOT12-SPOT12,NaN,NaN,NaN,NaN,NaN,NaN,INTERNAL NOTE 11 07 2019 16 46 37 ...,"[INTERNAL, NOTE, 11, 07, 2019, 16, 46, 37, 600..."
1,KUL,WP KUALA LUMPUR,6123,Careline,2000127122,220187543106,Billing - LPC,Bill Received,Bill Not Received,2019-07-14,...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
2,KUL,WP KUALA LUMPUR,6123,Careline,2000127225,220188432308,Billing - LPC,Bill Received,Bill Not Received,2019-07-15,...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
3,JOH,JOHOR,6340,Careline,2000125572,220728929002,Billing - LPC,Bill Received,Bill Not Received,2019-07-03,...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,NORMAL31-NORMAL31-NORMAL31-NORMAL31-NORMAL31-N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[nan]
4,NSE,NEGERI SEMBILAN,6320,Careline,2000127271,210108059707,MRU - OPC,Estimated Bill,Premise / Gate Not Locked,2019-07-15,...,ACT-ACT-ACT-ACT-EST-ACT-EST,SPOT11-SPOT11-SPOT11-SPOT11-SPOT11-SPOT11-SPOT11,NaN,NaN,NaN,NaN,NaN,NaN,INTERNAL NOTE15 07 2019 14 22 53 60068166PENGG...,"[INTERNAL, NOTE15, 07, 2019, 14, 22, 53, 60068..."

In [18]:
# assigning keywords
service_order_keywords = ['SERVICE ORDER', 'HAS BEEN TRANSFERRED']
#service_order_keywords = ['HAS BEEN TRANSFERRED']

In [19]:
sn_remarks['keywords'] = [service_order_keywords for _ in range(len(sn_remarks))]

In [20]:
# https://stackoverflow.com/questions/42683249/python-pandas-how-to-match-list-of-strings-with-a-dataframe-column
# Define function to search for words in two columns
def search_func(row):
    matches = [test_value in row["clean_sn_remark_grams"]
               for test_value in row["keywords"]]

    if all(matches):
        return 1
    else:
        return 0

In [21]:
sn_remarks['service_order_keywords_flag'] = sn_remarks.apply(search_func, axis=1)

In [22]:
sn_remarks.service_order_keywords_flag.value_counts()

0    15946
1     1972
Name: service_order_keywords_flag, dtype: int64

In [23]:
sn_remarks.shape

(17918, 92)

In [24]:
# Slecting SN REMARKS having service order value
sn_remarks_so = sn_remarks.loc[sn_remarks['service_order_keywords_flag'] == 1]

In [25]:
sn_remarks_so.shape

(1972, 92)

In [26]:
sn_remarks_so.columns

Index([                             'State',
                        'State_Description',
                      'Business_Area___Key',
                                  'Channel',
                             'Complaint_ID',
                                'CA_Number',
                                     'Unit',
                                 'Category',
                             'Sub_Category',
                            'Creation_Date',
                                'SN_Number',
                                'SO_Number',
                                'BPEM_Case',
                                    'Notes',
                        'SN_Remarks_25July',
                        'BPEM_Notes_24July',
                          'Feedback_Status',
                            'Status_25July',
                 'Verified_Root_Cause_Type',
                      'Verified_Root_Cause',
                       'Root_Cause_Measure',
                           'Refund/Arrears',
                             'Dt/Cr_Amount',
                                'MB_Reason',
                        'SO_transfer_to_SN',
                       'JAN_TOTAL_KWH_2019',
                       'FEB_TOTAL_KWH_2019',
                       'MAR_TOTAL_KWH_2019',
                       'APR_TOTAL_KWH_2019',
                       'MAY_TOTAL_KWH_2019',
                       'JUN_TOTAL_KWH_2019',
                       'JUL_BILL_DATE_2019',
                   'JUL_BILL_DURATION_2019',
                       'JUL_BILL_TYPE_2019',
                           'JUL_TARIF_TYPE',
                    'JUL_READING_TYPE_2019',
              'JUL_OUTSTANDING_AMOUNT_2019',
                 'JUL_CURRENT_CHARGES_2019',
                      'JUL_TOTAL_BILL_2019',
                       'JUL_TOTAL_KWH_2019',
       'JUL_BILLING_PERIOD_START_DATE_2019',
         'JUL_BILLING_PERIOD_END_DATE_2019',
                         'JUL_PORTION_2019',
                  'READING_TYPE_ENRICHMENT',
                           'Contains..FIN.',
                               'no.of.NA.s',
                             'JAN2019_BAND',
                             'FEB2019_BAND',
                             'MAR2019_BAND',
                             'APR2019_BAND',
                             'MAY2019_BAND',
                             'JUN2019_BAND',
                             'JUL2019_BAND',
                        'JAN2019_BANDRANGE',
                        'FEB2019_BANDRANGE',
                        'MAR2019_BANDRANGE',
                        'APR2019_BANDRANGE',
                        'MAY2019_BANDRANGE',
                        'JUN2019_BANDRANGE',
                        'JUL2019_BANDRANGE',
                         'FEB_KWH.Increase',
                         'MAR_KWH.Increase',
                         'APR_KWH.Increase',
                         'MAY_KWH.Increase',
                         'JUN_KWH.Increase',
                         'JUL_KWH.Increase',
                       'FEB2019_BANDCHANGE',
                       'MAR2019_BANDCHANGE',
                       'APR2019_BANDCHANGE',
                       'MAY2019_BANDCHANGE',
                       'JUN2019_BANDCHANGE',
                       'JUL2019_BANDCHANGE',
                      'FEB2019_CC.INCREASE',
                      'MAR2019_CC.INCREASE',
                      'APR2019_CC.INCREASE',
                      'MAY2019_CC.INCREASE',
                      'JUN2019_CC.INCREASE',
                      'JUL2019_CC.INCREASE',
                                'BILL_TYPE',
                               'TARRIFTYPE',
                             'READING_TYPE',
                                  'PORTION',
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                          'clean_sn_remark',
                    'clean_sn_remark_grams',
                                 'keywords',
              'service_order_keywords_flag'],
      dtype='object')

In [27]:
so_sn = sn_remarks_so

In [28]:
so_sn['Service Order'] = so_sn['clean_sn_remark'].str.extract(r'SERVICE ORDER\s+(.*?)\s+.')

C:\Users\ijohan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [29]:
so_sn['Service Notification'] =so_sn['clean_sn_remark'].str.extract(r'NEW SERVICE NOTIFICATION\s+(.*?)\s+.')

C:\Users\ijohan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [94]:
so_sn.to_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\faiztest.csv")

In [34]:
so_sn[['Service Order','Service Notification']].head()

    Service Order Service Notification
13   111000710162         220000645113
40   111000716600         220000648391
326  111000722093         220000653949
336  111000719613         220000650802
348  111000708717         220000643983

In [35]:
so_sn.shape

(1972, 94)

In [36]:
so_sn.columns

Index([                             'State',
                        'State_Description',
                      'Business_Area___Key',
                                  'Channel',
                             'Complaint_ID',
                                'CA_Number',
                                     'Unit',
                                 'Category',
                             'Sub_Category',
                            'Creation_Date',
                                'SN_Number',
                                'SO_Number',
                                'BPEM_Case',
                                    'Notes',
                        'SN_Remarks_25July',
                        'BPEM_Notes_24July',
                          'Feedback_Status',
                            'Status_25July',
                 'Verified_Root_Cause_Type',
                      'Verified_Root_Cause',
                       'Root_Cause_Measure',
                           'Refund/Arrears',
                             'Dt/Cr_Amount',
                                'MB_Reason',
                        'SO_transfer_to_SN',
                       'JAN_TOTAL_KWH_2019',
                       'FEB_TOTAL_KWH_2019',
                       'MAR_TOTAL_KWH_2019',
                       'APR_TOTAL_KWH_2019',
                       'MAY_TOTAL_KWH_2019',
                       'JUN_TOTAL_KWH_2019',
                       'JUL_BILL_DATE_2019',
                   'JUL_BILL_DURATION_2019',
                       'JUL_BILL_TYPE_2019',
                           'JUL_TARIF_TYPE',
                    'JUL_READING_TYPE_2019',
              'JUL_OUTSTANDING_AMOUNT_2019',
                 'JUL_CURRENT_CHARGES_2019',
                      'JUL_TOTAL_BILL_2019',
                       'JUL_TOTAL_KWH_2019',
       'JUL_BILLING_PERIOD_START_DATE_2019',
         'JUL_BILLING_PERIOD_END_DATE_2019',
                         'JUL_PORTION_2019',
                  'READING_TYPE_ENRICHMENT',
                           'Contains..FIN.',
                               'no.of.NA.s',
                             'JAN2019_BAND',
                             'FEB2019_BAND',
                             'MAR2019_BAND',
                             'APR2019_BAND',
                             'MAY2019_BAND',
                             'JUN2019_BAND',
                             'JUL2019_BAND',
                        'JAN2019_BANDRANGE',
                        'FEB2019_BANDRANGE',
                        'MAR2019_BANDRANGE',
                        'APR2019_BANDRANGE',
                        'MAY2019_BANDRANGE',
                        'JUN2019_BANDRANGE',
                        'JUL2019_BANDRANGE',
                         'FEB_KWH.Increase',
                         'MAR_KWH.Increase',
                         'APR_KWH.Increase',
                         'MAY_KWH.Increase',
                         'JUN_KWH.Increase',
                         'JUL_KWH.Increase',
                       'FEB2019_BANDCHANGE',
                       'MAR2019_BANDCHANGE',
                       'APR2019_BANDCHANGE',
                       'MAY2019_BANDCHANGE',
                       'JUN2019_BANDCHANGE',
                       'JUL2019_BANDCHANGE',
                      'FEB2019_CC.INCREASE',
                      'MAR2019_CC.INCREASE',
                      'APR2019_CC.INCREASE',
                      'MAY2019_CC.INCREASE',
                      'JUN2019_CC.INCREASE',
                      'JUL2019_CC.INCREASE',
                                'BILL_TYPE',
                               'TARRIFTYPE',
                             'READING_TYPE',
                                  'PORTION',
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                                        nan,
                          'clean_sn_remark',
                    'clean_sn_remark_grams',
                                 'keywords',
              'service_order_keywords_flag',
                            'Service Order',
                     'Service Notification'],
      dtype='object')

In [37]:
sn_remarks_so = sn_remarks_so[['State',
                        'State_Description',
                      'Business_Area___Key',
                                  'Channel',
                             'Complaint_ID',
                                'CA_Number',
                                     'Unit',
                                 'Category',
                             'Sub_Category',
                            'Creation_Date',
                                'SN_Number',
                                'SO_Number',
                                'BPEM_Case',
                                    'Notes',
                        'SN_Remarks_25July',
                        'BPEM_Notes_24July',
                          'Feedback_Status',
                            'Status_25July',
                 'Verified_Root_Cause_Type',
                      'Verified_Root_Cause',
                       'Root_Cause_Measure',
                           'Refund/Arrears',
                             'Dt/Cr_Amount',
                                'MB_Reason',
                        'SO_transfer_to_SN',
                       'JAN_TOTAL_KWH_2019',
                       'FEB_TOTAL_KWH_2019',
                       'MAR_TOTAL_KWH_2019',
                       'APR_TOTAL_KWH_2019',
                       'MAY_TOTAL_KWH_2019',
                       'JUN_TOTAL_KWH_2019',
                       'JUL_BILL_DATE_2019',
                   'JUL_BILL_DURATION_2019',
                       'JUL_BILL_TYPE_2019',
                           'JUL_TARIF_TYPE',
                    'JUL_READING_TYPE_2019',
              'JUL_OUTSTANDING_AMOUNT_2019',
                 'JUL_CURRENT_CHARGES_2019',
                      'JUL_TOTAL_BILL_2019',
                       'JUL_TOTAL_KWH_2019',
       'JUL_BILLING_PERIOD_START_DATE_2019',
         'JUL_BILLING_PERIOD_END_DATE_2019',
                         'JUL_PORTION_2019',
                  'READING_TYPE_ENRICHMENT',
                           'Contains..FIN.',
                               'no.of.NA.s',
                             'JAN2019_BAND',
                             'FEB2019_BAND',
                             'MAR2019_BAND',
                             'APR2019_BAND',
                             'MAY2019_BAND',
                             'JUN2019_BAND',
                             'JUL2019_BAND',
                        'JAN2019_BANDRANGE',
                        'FEB2019_BANDRANGE',
                        'MAR2019_BANDRANGE',
                        'APR2019_BANDRANGE',
                        'MAY2019_BANDRANGE',
                        'JUN2019_BANDRANGE',
                        'JUL2019_BANDRANGE',
                         'FEB_KWH.Increase',
                         'MAR_KWH.Increase',
                         'APR_KWH.Increase',
                         'MAY_KWH.Increase',
                         'JUN_KWH.Increase',
                         'JUL_KWH.Increase',
                       'FEB2019_BANDCHANGE',
                       'MAR2019_BANDCHANGE',
                       'APR2019_BANDCHANGE',
                       'MAY2019_BANDCHANGE',
                       'JUN2019_BANDCHANGE',
                       'JUL2019_BANDCHANGE',
                      'FEB2019_CC.INCREASE',
                      'MAR2019_CC.INCREASE',
                      'APR2019_CC.INCREASE',
                      'MAY2019_CC.INCREASE',
                      'JUN2019_CC.INCREASE',
                      'JUL2019_CC.INCREASE',
                                'BILL_TYPE',
                               'TARRIFTYPE',
                             'READING_TYPE',
                                  'PORTION',
                          'clean_sn_remark',
                    'clean_sn_remark_grams',
                                 'keywords',
              'service_order_keywords_flag',
                      'Service Order',
                     'Service Notification']]

In [100]:
sn_remarks_so.to_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\izzat_faiz_20190725_July_SRC_Main_List_SO_runJuly25.csv")

### find intersection of SO number data

In [38]:
import pandas as pd
import numpy as np
import sys
s1 = pd.read_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\izzat_faiz_20190725_July_SRC_Main_List_SO_runJuly25.csv")
#s2= pd.read_csv("C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\JUN_SOTRANSFER_STATUS_1JUN30JUN.csv")
s2= pd.read_excel(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\JUL_SOTRANSFER_STATUS_1JUL25JUL.xlsx")
s= pd.read_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\New SO Number July.csv")

In [39]:
s1.columns

Index(['Unnamed: 0', 'State', 'State_Description', 'Business_Area___Key',
       'Channel', 'Complaint_ID', 'CA_Number', 'Unit', 'Category',
       'Sub_Category', 'Creation_Date', 'SN_Number', 'SO_Number', 'BPEM_Case',
       'Notes', 'SN_Remarks_25July', 'BPEM_Notes_24July', 'Feedback_Status',
       'Status_25July', 'Verified_Root_Cause_Type', 'Verified_Root_Cause',
       'Root_Cause_Measure', 'Refund/Arrears', 'Dt/Cr_Amount', 'MB_Reason',
       'SO_transfer_to_SN', 'JAN_TOTAL_KWH_2019', 'FEB_TOTAL_KWH_2019',
       'MAR_TOTAL_KWH_2019', 'APR_TOTAL_KWH_2019', 'MAY_TOTAL_KWH_2019',
       'JUN_TOTAL_KWH_2019', 'JUL_BILL_DATE_2019', 'JUL_BILL_DURATION_2019',
       'JUL_BILL_TYPE_2019', 'JUL_TARIF_TYPE', 'JUL_READING_TYPE_2019',
       'JUL_OUTSTANDING_AMOUNT_2019', 'JUL_CURRENT_CHARGES_2019',
       'JUL_TOTAL_BILL_2019', 'JUL_TOTAL_KWH_2019',
       'JUL_BILLING_PERIOD_START_DATE_2019',
       'JUL_BILLING_PERIOD_END_DATE_2019', 'JUL_PORTION_2019',
       'READING_TYPE_ENRICHMENT', 'Contains..FIN.', 'no.of.NA.s',
       'JAN2019_BAND', 'FEB2019_BAND', 'MAR2019_BAND', 'APR2019_BAND',
       'MAY2019_BAND', 'JUN2019_BAND', 'JUL2019_BAND', 'JAN2019_BANDRANGE',
       'FEB2019_BANDRANGE', 'MAR2019_BANDRANGE', 'APR2019_BANDRANGE',
       'MAY2019_BANDRANGE', 'JUN2019_BANDRANGE', 'JUL2019_BANDRANGE',
       'FEB_KWH.Increase', 'MAR_KWH.Increase', 'APR_KWH.Increase',
       'MAY_KWH.Increase', 'JUN_KWH.Increase', 'JUL_KWH.Increase',
       'FEB2019_BANDCHANGE', 'MAR2019_BANDCHANGE', 'APR2019_BANDCHANGE',
       'MAY2019_BANDCHANGE', 'JUN2019_BANDCHANGE', 'JUL2019_BANDCHANGE',
       'FEB2019_CC.INCREASE', 'MAR2019_CC.INCREASE', 'APR2019_CC.INCREASE',
       'MAY2019_CC.INCREASE', 'JUN2019_CC.INCREASE', 'JUL2019_CC.INCREASE',
       'BILL_TYPE', 'TARRIFTYPE', 'READING_TYPE', 'PORTION', 'clean_sn_remark',
       'clean_sn_remark_grams', 'keywords', 'service_order_keywords_flag',
       'Service Order', 'Service Notification'],
      dtype='object')

In [40]:
s1.head()

,Unnamed: 0,State,State_Description,Business_Area___Key,Channel,Complaint_ID,CA_Number,Unit,Category,Sub_Category,...,BILL_TYPE,TARRIFTYPE,READING_TYPE,PORTION,clean_sn_remark,clean_sn_remark_grams,keywords,service_order_keywords_flag,Service Order,Service Notification
0,13,KUL,WP KUALA LUMPUR,6121,Kedai Tenaga,1000733239,220117626606,MRU - OPC,Check Meter Reading,Bill Too High,...,OPC-OPC-OPC-OPC-OPC-OPC-OPC,A:Kediaman-A:Kediaman-A:Kediaman-A:Kediaman-A:...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,SPOT19-SPOT19-SPOT19-SPOT19-SPOT19-SPOT19-SPOT19,INTERNAL NOTE 02 07 2019 09 25 53 ...,"['INTERNAL', 'NOTE', '02', '07', '2019', '09',...","['SERVICE ORDER', 'HAS BEEN TRANSFERRED']",1,111000710162,2.200006e+11
1,40,KUL,WP KUALA LUMPUR,6123,Careline,2000126927,220034993306,Device Operation (OPC),Meter Faulty,Meter Burnt,...,OPC-OPC-OPC-OPC-OPC-OPC-OPC,A:Kediaman-A:Kediaman-A:Kediaman-A:Kediaman-A:...,EST-EST-EST-EST-ACT-EST-ACT,SPOT27-SPOT27-SPOT27-SPOT27-SPOT27-SPOT27-SPOT27,INTERNAL NOTE 12 07 2019 11 56 58 60068144 FE...,"['INTERNAL', 'NOTE', '12', '07', '2019', '11',...","['SERVICE ORDER', 'HAS BEEN TRANSFERRED']",1,111000716600,2.200006e+11
2,326,KUL,WP KUALA LUMPUR,6121,Social Media,1000753061,220250692602,MRU - OPC,Check Meter Reading,Bill Too High,...,OPC-OPC-OPC-OPC-OPC-OPC-OPC,A:Kediaman-A:Kediaman-A:Kediaman-A:Kediaman-A:...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,SPOT18-SPOT18-SPOT18-SPOT18-SPOT18-SPOT18-SPOT18,0162038143 NAMA FB CHERIE ONG PENGGUNA MOHON...,"['0162038143', 'NAMA', 'FB', 'CHERIE', 'ONG', ...","['SERVICE ORDER', 'HAS BEEN TRANSFERRED']",1,111000722093,2.200007e+11
3,336,KUL,WP KUALA LUMPUR,6123,Careline,1000749032,220286739609,MRU - OPC,Check Meter Reading,Bill Too High,...,OPC-OPC-OPC-OPC-OPC-OPC-OPC,A:Kediaman-A:Kediaman-A:Kediaman-A:Kediaman-A:...,ACT-ACT-ACT-ACT-ACT-ACT-ACT,SPOT06-SPOT06-SPOT06-SPOT06-SPOT06-SPOT06-SPOT06,INTERNAL NOTE12 07 2019 19 41 22 C035582 PENGG...,"['INTERNAL', 'NOTE12', '07', '2019', '19', '41...","['SERVICE ORDER', 'HAS BEEN TRANSFERRED']",1,111000719613,2.200007e+11
4,348,KUL,WP KUALA LUMPUR,6124,Careline,1000731828,220129945110,MRU - OPC,Check Meter Reading,Bill Too High,...,OPC-OPC-OPC-OPC-OPC-OPC-OPC,B:Perdagangan-B:Perdagangan-B:Perdagangan-B:Pe...,ACT-ACT-EST-ACT-ACT-ACT-ACT,SPOT26-SPOT25-SPOT25-SPOT25-SPOT27-SPOT27-SPOT27,HASIL LAWATAN TAPAK DI DAPATI PREMIS ADALAH CA...,"['HASIL', 'LAWATAN', 'TAPAK', 'DI', 'DAPATI', ...","['SERVICE ORDER', 'HAS BEEN TRANSFERRED']",1,111000708717,2.200006e+11

In [41]:
s2.shape

(3383, 25)

In [42]:
s.shape

(1622, 2)

In [43]:
s.head()

   Notification         Order
0  218000653115  111000710124
1  218000653116  111000710125
2  218000654520  111000711438
3  218000654521  111000711439
4  218000654522  111000711520

In [44]:
s2.columns

Index(['Order', 'Order Type', 'Code group', 'Code', 'Contract Account',
       'Installation', 'Installation Type', 'Business Partner Name', 'Address',
       'Primary Tel Number', 'Secondary Tel Number',
       'Service Order System Status', 'Service Order User Status', 'Use',
       'Manufacturer of asset', 'CT Num', 'CT Den', 'Device Serial Number',
       'Device Location Text', 'Initiated/Updated By', 'Executed By',
       'Created On', 'Aging (days)', 'KIV Date', 'Act. Finish Date'],
      dtype='object')

In [45]:
s2 = s2[['Order','Contract Account','Created On','Service Order System Status']]

In [46]:
s1 = s1.rename(columns={'Service Notification': 'Notification'})

In [47]:
#merging so created file with unique notification and order ID
s1_s = pd.merge(s1, s, how='inner', on='Notification')
#final = pd.join(s1, s2, how='left', on='Contract_Account')

In [60]:
s1_s.to_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\testing.csv")

In [48]:
s1_s.shape

(1632, 90)

In [49]:
s1_s = s1_s.loc[:, "State":"Order"]

In [115]:
s1_s.to_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\izzatfaiz_notification_july.csv")

In [50]:
s1_s.columns

Index(['State', 'State_Description', 'Business_Area___Key', 'Channel',
       'Complaint_ID', 'CA_Number', 'Unit', 'Category', 'Sub_Category',
       'Creation_Date', 'SN_Number', 'SO_Number', 'BPEM_Case', 'Notes',
       'SN_Remarks_25July', 'BPEM_Notes_24July', 'Feedback_Status',
       'Status_25July', 'Verified_Root_Cause_Type', 'Verified_Root_Cause',
       'Root_Cause_Measure', 'Refund/Arrears', 'Dt/Cr_Amount', 'MB_Reason',
       'SO_transfer_to_SN', 'JAN_TOTAL_KWH_2019', 'FEB_TOTAL_KWH_2019',
       'MAR_TOTAL_KWH_2019', 'APR_TOTAL_KWH_2019', 'MAY_TOTAL_KWH_2019',
       'JUN_TOTAL_KWH_2019', 'JUL_BILL_DATE_2019', 'JUL_BILL_DURATION_2019',
       'JUL_BILL_TYPE_2019', 'JUL_TARIF_TYPE', 'JUL_READING_TYPE_2019',
       'JUL_OUTSTANDING_AMOUNT_2019', 'JUL_CURRENT_CHARGES_2019',
       'JUL_TOTAL_BILL_2019', 'JUL_TOTAL_KWH_2019',
       'JUL_BILLING_PERIOD_START_DATE_2019',
       'JUL_BILLING_PERIOD_END_DATE_2019', 'JUL_PORTION_2019',
       'READING_TYPE_ENRICHMENT', 'Contains..FIN.', 'no.of.NA.s',
       'JAN2019_BAND', 'FEB2019_BAND', 'MAR2019_BAND', 'APR2019_BAND',
       'MAY2019_BAND', 'JUN2019_BAND', 'JUL2019_BAND', 'JAN2019_BANDRANGE',
       'FEB2019_BANDRANGE', 'MAR2019_BANDRANGE', 'APR2019_BANDRANGE',
       'MAY2019_BANDRANGE', 'JUN2019_BANDRANGE', 'JUL2019_BANDRANGE',
       'FEB_KWH.Increase', 'MAR_KWH.Increase', 'APR_KWH.Increase',
       'MAY_KWH.Increase', 'JUN_KWH.Increase', 'JUL_KWH.Increase',
       'FEB2019_BANDCHANGE', 'MAR2019_BANDCHANGE', 'APR2019_BANDCHANGE',
       'MAY2019_BANDCHANGE', 'JUN2019_BANDCHANGE', 'JUL2019_BANDCHANGE',
       'FEB2019_CC.INCREASE', 'MAR2019_CC.INCREASE', 'APR2019_CC.INCREASE',
       'MAY2019_CC.INCREASE', 'JUN2019_CC.INCREASE', 'JUL2019_CC.INCREASE',
       'BILL_TYPE', 'TARRIFTYPE', 'READING_TYPE', 'PORTION', 'clean_sn_remark',
       'clean_sn_remark_grams', 'keywords', 'service_order_keywords_flag',
       'Service Order', 'Notification', 'Order'],
      dtype='object')

In [396]:
#d = s1['Contract_Account'].isin(s2['Contract_Account'])

In [51]:
s2.head()

          Order  Contract Account Created On Service Order System Status
0  113000812315      2.202680e+11 2019-07-03       Technically Completed
1  113000812357      2.202431e+11 2019-07-03                    Released
2  113000812405      2.101264e+11 2019-07-03       Technically Completed
3  113000812460      2.207728e+11 2019-07-03                    Released
4  113000812425      2.101311e+11 2019-07-03       Technically Completed

In [52]:
#final = pd.merge(s1, s2, how='left', on='Contract_Account')
final = pd.merge(s1_s, s2, how='inner', on='Order')

In [73]:
#final2 = pd.merge(s1_s, s2, how='right', on='Order')

In [75]:
#final3 = pd.merge(s1_s, s2, how='left', on='Order')

In [399]:
#final = final.dropna(subset=['Service Order System Status'])

In [400]:
#final = final.drop_duplicates(subset='Contract_Account', keep="last")

In [119]:
final.shape

(1491, 92)

In [120]:
final.to_csv(r"C:\Users\ijohan\Desktop\SO_SN\JULY_SO_SN\izzat_final_july.csv")